Corrected the error in the accel_math.py file
AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
Simply replaced `np.NaN` with `np.nan` in the accel_math.py file.